model:
    debug_print_flag: False #Use 1 (True) to enable or 0 (False) to disable.
    weight_fn: None #True #False #TOTEST

dataset:
    github_data_path: "data/openEDS"
    data_path: "datasets/mobious/MOBIOUS/processed"
    models_path: "datasets/ready/openEDS/models"
    checkpoint_path: "datasets/?"

model_hyperparameters:
    batch_size: 8
    num_workers: 0
    epochs: 5
    #epochs: 100
    learning_rate: 0.003
