model:
    input_model_name: "30-Jul-2025_22-34-06_NVIDIA_A100_80GB_PCI/weights_30-Jul-2025_22-34-06.pth"

dataset:
    models_path: "Scratch/scratch/ccaekqu/datasets/ready/ready/mobious/models"
    github_data_path: "data/mobious"
    data_path: "Scratch/scratch/ccaekqu/datasets/mobious/mobious/MOBIOUS/train100per_1144"  ##CHANGE TO TEST IMAGE PATH WHEN U FIND ONE, LEAVING AT MOBIOUS FOR NOW
    checkpoint_path: "datasets/?"
    inference_results: "Scratch/scratch/ccaekqu/datasets/ready/ready/inference"     ##store output results of inference
